version: '3.8'

x-bot-scan-web-base: &bot-scan-web-base
  image: registry.codewalk.myds.me/binance-futures-scan-web:${API_TAG}
  restart: unless-stopped
  environment:
    TRADING_CONFIG_DIR: /app/trading_config.json
  mem_limit: 1536m
  # cpus: 1.5  # Commented out: kernel does not support CPU CFS scheduler
services:

  bot-scan-web:
    <<: *bot-scan-web-base
    container_name: binance-future-scan-web
    ports:
      - "8501:8501"
    restart: unless-stopped
    environment:
      - API_BASE_URL=https://futures-signal-api.codewalk.myds.me
      - PORT=8501
  