version: '3.8'

services:
  future-bot-web-film-8005:
    image: registry.codewalk.myds.me/binance-futures-bot-web:2025.12.20-2
    container_name: binance-future-web-film-8005
    ports:
      - "8005:8005"
    restart: unless-stopped
    environment:
      - API_BASE_URL=https://fbot-api.codewalk.myds.me
      - PORT=8005
  
  future-bot-api-film-8006:
    image: registry.codewalk.myds.me/binance-futures-bot-api:2025.12.20-3
    container_name: binance-future-api-film-8006
    ports:
      - "8006:8006"
    restart: unless-stopped
    environment:
      - PORT=8006
      - TRADING_CONFIG_DIR=/app/trading_config.json
    volumes:
      - /volume1/docker/bot-future-config/futurebot-api-film/trading_config.json:/app/trading_config.json:rw
  